
name: "CI"
on: [push]

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-22.04
    container: springci/spring-framework-ci:5.2.x
    steps:
      - uses: actions/checkout@v2
      - name: Pre CI script
        if: ${{ hashFiles('.seal/pre_ci_script.sh') != '' }}
        run: |
          .seal/pre_ci_script.sh
      - name: "Build"
        run: |
          ./gradlew build
      - name: "Upload jars"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "jars"
          path: "**/*.jar"
      - name: "Upload test results"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "build-results"
          path: "**/build/reports"
